default: &default
  adapter: postgresql
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  adapter: postgresql
  encoding: unicode
  database: babel_assignment_development
  port: 5432
  pool: 5

test:
  adapter: postgresql
  encoding: unicode
  database: babel_assignment_test
  port: 5432
  pool: 5
